----- Script de Vistas -----

CREATE OR REPLACE VIEW VISTA_DUEÑO AS SELECT ID_DUEÑO,NOMBRE,USUARIO,CONTRASEÑA
FROM DUEÑO
WHERE DISPONIBILIDAD = 'E'
WITH CHECK OPTION;

CREATE OR REPLACE VIEW VISTA_EQUIPO AS SELECT ID_EQUIPO,NOMBRE,SALARIO_TOTAL,ID_DUENIO
FROM EQUIPO
WHERE DISPONIBILIDAD = 'E'
WITH CHECK OPTION;

CREATE OR REPLACE VIEW JUGADORES_DISPONIBLES AS 
SELECT * FROM JUGADOR WHERE ID_JUGADOR IN(
SELECT DISTINCT ID_JUGADOR FROM JUGADOR_EQUIPO WHERE FECHA_FIN IS NOT NULL AND ID_JUGADOR 
NOT IN(SELECT ID_JUGADOR FROM JUGADOR_EQUIPO WHERE FECHA_FIN IS NULL))
WITH READ ONLY;

