create table Administrador(
id_admin number(10) constraint id_admin_pk primary key ,
contraseña varchar2(20) not null,
usuario varchar2(50) not null
);

create table Dueño(
id_dueño number(10) constraint id_dueño_pk primary key,
nombre varchar2(50) not null,
contraseña varchar2(20) not null,
usuario varchar2(50) not null
);

CREATE TABLE Jugador(
id_jugador NUMBER(10) CONSTRAINT id_jugador_pk PRIMARY KEY,
nombre VARCHAR2(50) NOT NULL,
nickname VARCHAR2(50) NOT NULL,
sueldo NUMBER(10) NOT NULL
);

CREATE TABLE Jugador_Equipo(
id_jugador NUMBER(10) NOT NULL CONSTRAINT id_jugador_fk REFERENCES Jugador,
id_equipo NUMBER(10) NOT NULL CONSTRAINT id_equipo_fk REFERENCES Equipo,
fecha_inicio date NOT NULL,
fecha_fin date NOT NULL,
CONSTRAINT jef_pk PRIMARY KEY(id_jugador, id_equipo, fecha_inicio)
);


CREATE TABLE CALENDARIO(
ID_TEMPORADA NUMBER(10) CONSTRAINT PK_CAL PRIMARY KEY,
FECHA_INICIO DATE CONSTRAINT NN_FEC_IN NOT NULL,
FECHA_FIN DATE CONSTRAINT NN_FEC_FIN NOT NULL

);

CREATE TABLE JORNADA(
ID_JORNADA NUMBER(10) CONSTRAINT PK_JOR PRIMARY KEY,
FECHA DATE CONSTRAINT NN_FEC NOT NULL,
ID_TEMPORADA NUMBER(10) CONSTRAINT FK_JOR  REFERENCES CALENDARIO  

);

CREATE TABLE EQUIPO(
	ID_EQUIPO NUMBER(10) CONSTRAINT EQUI_ID_PK PRIMARY KEY,
	NOMBRE VARCHAR2(100) CONSTRAINT EQUI_NOM_UK UNIQUE,
	SALARIO_TOTAL NUMBER(10),
	ID_DUENIO NUMBER(10) CONSTRAINT EQUI_DUENIO_FK REFERENCES DUEÑO ON DELETE CASCADE,
	CONSTRAINT EQUI_NN NOT NULL(NOMBRE,SALARIO_TOTAL)
);

CREATE TABLE PARTIDO(
	ID_PARTIDO NUMBER(10) CONSTRAINT PART_ID_PK PRIMARY KEY,
	GANADOR NUMBER(10),
	MARCADOR_LOCAL NUMBER(10),
	MARCADOR_VISITANTE NUMBER(10),
	EQUIPO_LOCAL NUMBER(10) CONSTRAINT PART_LOCAL_FK REFERENCES EQUIPO ON DELETE SET NULL,
	EQUIPO_VISITANTE NUMBER(10)CONSTRAINT PART_VISITAL_FK REFERENCES EQUIPO ON DELETE SET NULL,
	JORNADA NUMBER(10) CONSTRAINT PART_JOR_FK REFERENCES JORNADA	
);