
CREATE TABLE CALENDARIO(
ID_TEMPORADA NUMBER(10) CONSTRAINT PK_CAL PRIMARY KEY,
FECHA_INICIO DATE CONSTRAINT NN_FEC_IN NOT NULL,
FECHA_FIN DATE CONSTRAINT NN_FEC_FIN NOT NULL

);

CREATE TABLE JORNADA(
ID_JORNADA NUMBER(10) CONSTRAINT PK_JOR PRIMARY KEY,
FECHA DATE CONSTRAINT NN_FEC NOT NULL,
ID_TEMPORADA NUMBER(10) CONSTRAINT FK_JOR FOREIGN KEY REFERENCES CALENDARIO  

);

