CREATE OR REPLACE VIEW VISTA_DUEÑO AS SELECT ID_DUEÑO,NOMBRE,USUARIO,CONTRASEÑA
FROM DUEÑO
WHERE DISPONIBILIDAD = 'E'
WITH CHECK OPTION;

CREATE OR REPLACE VIEW VISTA_EQUIPO AS SELECT ID_EQUIPO,NOMBRE,SALARIO_TOTAL,ID_DUENIO
FROM EQUIPO
WHERE DISPONIBILIDAD = 'E'
WITH CHECK OPTION;

